services:
  ttpham.projects.listener:
    class: ttpham\projects\event\listener
    arguments:
      - @auth
      - @config
      - @dbal.conn
      - @controller.helper
      - @mimetype.guesser
      - @notification_manager
      - @plupload
      - @request
      - @template
      - @user
      - @ttpham.projects.projects_helper
      - @ttpham.projects.controller
      - %core.php_ext%
      - %core.root_path%
      - %core.table_prefix%
    tags:
      - { name: event.listener }

  ttpham.projects.controller:
    class: ttpham\projects\controller\main
    arguments:
      - @auth
      - @config
      - @dbal.conn
      - @notification_manager
      - @request
      - @template
      - @user
      - @ttpham.projects.projects_helper
      - %core.php_ext%
      - %core.root_path%
      - %core.table_prefix%

  ttpham.projects.cron.task.prune_projects:
    class: ttpham\projects\cron\task\prune_projects
    arguments:
      - @config
      - @ttpham.projects.projects_helper
    calls:
      - [set_name, [cron.task.prune_projects]]
    tags:
      - { name: prune.projects }

  ttpham.projects.cron.task.prune_releases:
    class: ttpham\projects\cron\task\prune_releases
    arguments:
      - @config
      - @ttpham.projects.projects_helper
    calls:
      - [set_name, [cron.task.prune_releases]]
    tags:
      - { name: prune.releases }

  ttpham.projects.notification.type.release_request:
    class: ttpham\projects\notification\release_request
    scope: prototype
    arguments:
      - @user_loader
      - @dbal.conn
      - @cache.driver
      - @user
      - @auth
      - @config
      - %core.root_path%
      - %core.php_ext%
      - %tables.notification_types%
      - %tables.notifications%
      - %tables.user_notifications%
    tags:
      - { name: notification.type }

  ttpham.projects.projects_helper:
    class: ttpham\projects\services\projects_helper
    arguments:
      - @auth
      - @config
      - @dbal.conn.driver
      - @user
      - %core.table_prefix%