services:
  ttpham.projects.listener:
    class: ttpham\projects\event\listener
    arguments:
      - @auth
      - @config
      - @dbal.conn
      - @controller.helper
      - @request
      - @template
      - @user
      - @ttpham.projects.projects_helper
      - @ttpham.projects.controller
      - %core.table_prefix%
    tags:
      - { name: event.listener }

  ttpham.projects.controller:
    class: ttpham\projects\controller\main
    arguments:
      - @auth
      - @config
      - @dbal.conn
      - @template
      - @user
      - @ttpham.projects.projects_helper
      - %core.php_ext%
      - %core.root_path%
      - %core.table_prefix%

  ttpham.projects.projects_helper:
    class: ttpham\projects\services\projects_helper
    arguments:
      - @auth
      - @config
      - @dbal.conn.driver
      - @user
      - %core.table_prefix%